name: Daily Sync Workflow File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Download workflow file
      run: |
        mkdir -p .github/workflows
        curl -L https://raw.githubusercontent.com/NT-AUTHORITY/Spigot-Build-Automated/refs/heads/main/.github/workflows/build-spigot.yml -o .github/workflows/build-spigot.yml

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .github/workflows/build-spigot.yml
        git commit -m "Daily update of build-spigot.yml from Spigot-Build-Automated"
        git push
