name: Sync Workflows to /src

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 自动运行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Create /src directory if it doesn't exist
      run: mkdir -p src

    - name: Download workflow files from the other repository
      run: |
        curl -L https://raw.githubusercontent.com/NT-AUTHORITY/Spigot-Build-Automated/main/.github/workflows/build-spigot.yml -o src/build-spigot.yml

    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add src/build-spigot.yml
        git commit -m "Synced build-spigot.yml from Spigot-Build-Automated to /src" || echo "No changes to commit"
        git push https://x-access-token:${TOKEN}@github.com/NT-AUTHORITY/Actions.git -f
