name: Daily Sync Workflow File

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 自动运行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Download workflow file (Force Sync)
      run: |
        mkdir -p /src
        curl -L https://raw.githubusercontent.com/NT-AUTHORITY/Spigot-Build-Automated/refs/heads/main/.github/workflows/build-spigot.yml -o .github/workflows/build-spigot.yml

    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .github/workflows/build-spigot.yml
        git commit -m "Forced sync of build-spigot.yml from Spigot-Build-Automated" || echo "No changes to commit"
        git push https://x-access-token:${TOKEN}@github.com/NT-AUTHORITY/Actions.git -f
